<a href="https://colab.research.google.com/github/Ravravan/ML/blob/main/Encoding_categorical_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



#ORDINAL ENCODING

In [397]:
import pandas as pd
import numpy as np

In [398]:
df = pd.read_csv('customer.csv')

In [399]:
df.sample(5)

    age  gender   review education purchased
36   34  Female     Good        UG       Yes
7    60  Female     Poor    School       Yes
27   69  Female     Poor        PG        No
40   39    Male     Good    School        No
34   86    Male  Average    School        No

In [400]:
df =df.iloc[:,2:]

In [401]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [402]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1],test_size=0.2)

In [403]:
x_train

     review education
8   Average        UG
19     Poor        PG
23     Good    School
14     Poor        PG
33     Good        PG
26     Poor        PG
16     Poor        UG
9      Good        UG
29  Average        UG
11     Good        UG
42     Good        PG
46     Poor        PG
12     Poor    School
2      Good        PG
15     Poor        UG
37  Average        PG
17     Poor        UG
27     Poor        PG
6      Good    School
44  Average        UG
40     Good    School
1      Poor        UG
7      Poor    School
18     Good    School
48     Good        UG
21  Average        PG
47     Good        PG
28     Poor    School
39     Poor        PG
31     Poor    School
10     Good        UG
30  Average        UG
22     Poor        PG
36     Good        UG
25     Good    School
24  Average        PG
5   Average    School
49     Good        UG
20  Average    School
34  Average    School

In [404]:
from sklearn.preprocessing import OrdinalEncoder

In [405]:
ordinal_encoder = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [406]:
ordinal_encoder.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [407]:
x_train = ordinal_encoder.transform(x_train)
x_test = ordinal_encoder.transform(x_test)

In [408]:
x_train

array([[1., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [1., 2.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 2.],
       [1., 0.],
       [2., 1.],
       [1., 0.],
       [1., 0.]])

In [409]:
from sklearn.preprocessing import LabelEncoder

In [410]:
le = LabelEncoder()

In [411]:
le.fit(y_train)

LabelEncoder()

In [412]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [413]:
y_train =le.transform(y_train)
y_test = le.transform(y_test)

In [414]:
y_train

array([0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0])


#ONE HOT ENCODING

In [415]:
df = pd.read_csv('cars.csv')

In [416]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [417]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [418]:
df['brand'].nunique()

32

In [419]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [420]:
df["owner"].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [421]:
#one hot encoding using pandas

pd.get_dummies(df,columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [422]:
#k-1 enconing
pd.get_dummies(df,columns=['fuel', 'owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [423]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [424]:
#one hot enconding using sklearn

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=2)

In [425]:
x_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [426]:
x_test.head()

         brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner

In [427]:
from sklearn.preprocessing import OneHotEncoder

In [428]:
ohe=OneHotEncoder(drop='first',dtype=np.int32)

In [429]:
ohe.fit_transform(x_train[['fuel','owner']])

<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 8746 stored elements and shape (6502, 7)>

In [430]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [431]:
x_test_new =ohe.transform(x_test[['fuel','owner']]).toarray()

In [432]:
x_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [433]:
x_train[['brand','km_driven']].values

array([['Hyundai', 35000],
       ['Jeep', 60000],
       ['Hyundai', 25000],
       ...,
       ['Tata', 15000],
       ['Maruti', 32500],
       ['Isuzu', 121000]], dtype=object)

In [434]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [435]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)).shape

(6502, 9)

In [436]:
counts =df['brand'].value_counts()

In [437]:
df['brand'].unique()
threshold = 100

In [438]:
counts[counts <= threshold].index

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [439]:
repl = counts[counts <= threshold].index
pd.get_dummies(df['brand'].replace(repl, 'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False

#COLUMN TRANSFORMER

In [440]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [441]:
df=pd.read_csv('covid_toy.csv')

In [442]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [443]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [444]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [445]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [446]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, _test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [447]:
x_train

    age  gender  fever   cough       city
76   80    Male  100.0    Mild  Bangalore
51   11  Female  100.0  Strong    Kolkata
66   51    Male  104.0    Mild    Kolkata
73   34    Male   98.0  Strong    Kolkata
74   34  Female  104.0  Strong      Delhi
..  ...     ...    ...     ...        ...
5    84  Female    NaN    Mild  Bangalore
43   22  Female   99.0    Mild  Bangalore
4    65  Female  101.0    Mild     Mumbai
7    20  Female    NaN  Strong     Mumbai
54   60  Female   99.0    Mild     Mumbai

[80 rows x 5 columns]

In [448]:

#without columns transformer

#adding simple imputer to fever col

si =SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])

#also the test dats

x_test_fever =si.fit_transform(x_test[['fever']])
x_train_fever

array([[100.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [103.        ],
       [103.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [100.        ],
       [102.        ],
       [104.        ],
       [102.        ],
       [ 99.        ],
       [101.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [100.80555556],
       [ 98.        ],
       [101.        ],
       [100.80555556],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [103.        ],
       [101.        ],
       [102.        ],
       [103.        ],
       [100.        ],
       [100.80555556],
       [103.        ],
       [100.80555556],
       [104.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [103.        ],
       [ 98.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [104.        ],
       [102.        ],
       [101.        ],
       [ 99.        ],
       [100.80555556],
       [104.        ],
       [ 98.        ],
       [100.80555556],
       [104.        ],
       [100.        ],
       [ 99.        ],
       [100.        ],
       [100.        ],
       [100.80555556],
       [ 99.        ],
       [101.        ],
       [100.80555556],
       [ 99.        ]])

In [449]:
x_train_fever.shape

(80, 1)

In [450]:
#ordinal encoding -> cough

oe =OrdinalEncoder(categories=[['Mild', 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

#also  the tesg data

x_test_cough = oe.transform(x_test[['cough']])
x_train_cough

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [451]:
x_train_cough.shape

(80, 1)

In [458]:
#onhotencoding -> gender,city
ohe=OneHotEncoder(drop='first')
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']]).toarray()

#also the test data
x_test_gender_city =ohe.fit_transform(x_test[['gender','city']]).toarray()
x_train_gender_city.shape

(80, 4)

In [459]:
#extrscing age
x_train_age = x_train.drop(columns=['gender','fever','city','cough']).values
x_test_age = x_test.drop(columns=['gender','fever','city', 'cough']).values

In [460]:
x_train_age

array([[80],
       [11],
       [51],
       [34],
       [34],
       [69],
       [70],
       [12],
       [23],
       [51],
       [81],
       [47],
       [64],
       [51],
       [ 5],
       [25],
       [68],
       [44],
       [11],
       [69],
       [47],
       [15],
       [64],
       [74],
       [69],
       [10],
       [82],
       [ 5],
       [40],
       [81],
       [42],
       [26],
       [49],
       [23],
       [83],
       [50],
       [24],
       [80],
       [59],
       [66],
       [19],
       [27],
       [ 6],
       [48],
       [20],
       [82],
       [73],
       [27],
       [34],
       [83],
       [38],
       [17],
       [83],
       [19],
       [42],
       [19],
       [65],
       [60],
       [73],
       [24],
       [49],
       [13],
       [56],
       [20],
       [42],
       [14],
       [71],
       [75],
       [31],
       [82],
       [16],
       [55],
       [72],
       [27],
       [19],
       [84],
       [22],
       [65],
       [20],
       [60]])

In [461]:
x_train_age.shape

(80, 1)

In [462]:
x_train_transformed = np.concatenate((x_train_age, x_train_fever, x_train_gender_city, x_train_cough), axis=1)
x_test_transformed = np.concatenate((x_test_age, x_test_fever, x_test_gender_city, x_test_cough), axis =1)

In [464]:
x_train_transformed.shape

(80, 7)

In [465]:
#with column transformer
from sklearn.compose import ColumnTransformer

In [466]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender','city']),

], remainder='passthrough')

In [468]:
transformer.fit_transform(x_train)

array([[100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  80.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  11.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [103.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  70.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [101.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  51.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  51.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  68.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  44.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  11.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  69.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  15.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [102.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  74.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  69.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  10.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  82.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  40.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [100.80555556,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  26.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [100.80555556,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [ 98.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  83.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  50.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  24.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  59.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  19.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  27.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   6.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  48.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [102.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  82.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  73.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [100.80555556,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [100.80555556,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  38.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  17.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  19.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  65.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  24.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  13.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [102.        ,   1.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  20.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [100.80555556,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  31.        ],
       [100.80555556,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  82.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  55.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  19.        ],
       [100.80555556,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  84.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  22.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [100.80555556,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  60.        ]])

In [469]:
transformer.fit_transform(x_train).shape

(80, 7)

In [470]:
transformer.transform(x_test)

array([[103.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  46.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   8.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  16.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  64.        ],
       [ 99.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  65.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  38.        ],
       [100.80555556,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  79.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  71.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  14.        ],
       [100.80555556,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  18.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  25.        ],
       [102.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  49.        ],
       [102.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  33.        ]])

In [471]:
transformer.transform(x_test).shape

(20, 7)