<a href="https://colab.research.google.com/github/Ravravan/ML/blob/main/Encoding_categorical_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



#ORDINAL ENCODING

In [96]:
import pandas as pd
import numpy as np

In [97]:
df = pd.read_csv('customer.csv')

In [98]:
df.sample(5)

    age  gender   review education purchased
5    31  Female  Average    School       Yes
13   57  Female  Average    School        No
43   27    Male     Poor        PG        No
6    18    Male     Good    School        No
48   39  Female     Good        UG       Yes

In [99]:
df =df.iloc[:,2:]

In [100]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [101]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1],test_size=0.2)

In [102]:
x_train

     review education
17     Poor        UG
32  Average        UG
15     Poor        UG
24  Average        PG
4   Average        UG
0   Average    School
16     Poor        UG
43     Poor        PG
3      Good        PG
35     Poor    School
14     Poor        PG
37  Average        PG
5   Average    School
34  Average    School
39     Poor        PG
48     Good        UG
26     Poor        PG
2      Good        PG
20  Average    School
30  Average        UG
45     Poor        PG
22     Poor        PG
41     Good        PG
12     Poor    School
8   Average        UG
40     Good    School
29  Average        UG
6      Good    School
27     Poor        PG
1      Poor        UG
9      Good        UG
28     Poor    School
11     Good        UG
7      Poor    School
25     Good    School
19     Poor        PG
21  Average        PG
42     Good        PG
18     Good    School
47     Good        PG

In [103]:
from sklearn.preprocessing import OrdinalEncoder

In [104]:
ordinal_encoder = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [105]:
ordinal_encoder.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [106]:
x_train = ordinal_encoder.transform(x_train)
x_test = ordinal_encoder.transform(x_test)

In [107]:
x_train

array([[0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [2., 0.],
       [2., 2.]])

In [108]:
from sklearn.preprocessing import LabelEncoder

In [109]:
le = LabelEncoder()

In [110]:
le.fit(y_train)

LabelEncoder()

In [111]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [112]:
y_train =le.transform(y_train)
y_test = le.transform(y_test)

In [113]:
y_train

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1])


#ONE HOT ENCODING

In [114]:
df = pd.read_csv('cars.csv')

In [115]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [116]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [117]:
df['brand'].nunique()

32

In [118]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [119]:
df["owner"].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [120]:
#one hot encoding using pandas

pd.get_dummies(df,columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

In [121]:
#k-1 enconing
pd.get_dummies(df,columns=['fuel', 'owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [122]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [123]:
#one hot enconding using sklearn

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=2)

In [124]:
x_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [125]:
x_test.head()

         brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner

In [126]:
from sklearn.preprocessing import OneHotEncoder

In [127]:
ohe=OneHotEncoder(drop='first',dtype=np.int32)

In [128]:
ohe.fit_transform(x_train[['fuel','owner']])

<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 8746 stored elements and shape (6502, 7)>

In [129]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [130]:
x_test_new =ohe.transform(x_test[['fuel','owner']]).toarray()

In [131]:
x_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [132]:
x_train[['brand','km_driven']].values

array([['Hyundai', 35000],
       ['Jeep', 60000],
       ['Hyundai', 25000],
       ...,
       ['Tata', 15000],
       ['Maruti', 32500],
       ['Isuzu', 121000]], dtype=object)

In [133]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [134]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)).shape

(6502, 9)

In [137]:
counts =df['brand'].value_counts()

In [138]:
df['brand'].unique()
threshold = 100

In [139]:
counts[counts <= threshold].index

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [141]:
repl = counts[counts <= threshold].index
pd.get_dummies(df['brand'].replace(repl, 'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False