<a href="https://colab.research.google.com/github/Ravravan/ML/blob/main/Handling_date_time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [7]:
#Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

#1.EXTRACT DATE

In [10]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
443 2018-09-21         873       25      16       2018
662 2019-07-08        6290       23       1       2019
15  2019-02-14         202        2       4       2019
169 2019-03-25        2876        1       4       2019
51  2019-08-12        6344       26       1       2019

#2.EXTRACT MONTH

In [11]:
date['date_month_no'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
536 2019-04-24        1140       26       2       2019              4
510 2019-04-04        5953       13      34       2019              4
196 2018-08-20        6215       22       4       2018              8
326 2019-10-29        1675        4       2       2019             10
397 2019-06-25        6435       13       1       2019              6

In [12]:
date['date_month_no'] = date['date'].dt.month_name()
date.sample(5)

          date  product_id  city_id  orders  date_year date_month_no
527 2019-08-01        2811       13       2       2019        August
774 2019-08-17        2459        0       8       2019        August
929 2019-12-07        6801        3       7       2019      December
732 2019-08-15        5143       16       2       2019        August
906 2019-02-18        5428       26       1       2019      February

#3. EXTRACT DAYS

In [13]:
date['date_day'] = date['date'].dt.day
date.sample(5)

          date  product_id  city_id  orders  date_year date_month_no  date_day
504 2019-04-23        5280       23       8       2019         April        23
110 2019-08-13        7059       14      11       2019        August        13
366 2019-07-22        2307        4       6       2019          July        22
27  2019-01-24        4152       28       2       2019       January        24
67  2018-11-18        3604       16       5       2018      November        18

In [14]:
#day of week
date['date_dow'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
978,2018-11-13,2845,23,2,2018,November,13,1
307,2018-12-06,3034,0,1,2018,December,6,3
828,2019-04-22,6933,25,43,2019,April,22,0
832,2019-01-11,4445,25,1,2019,January,11,4
216,2019-12-13,3493,26,9,2019,December,13,4

In [19]:
#day of week - name
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id', 'city_id', 'orders']).head()

        date  date_year date_month_no  date_day   date_dow date_dow_name
0 2019-12-10       2019      December        10    Tuesday       Tuesday
1 2018-08-15       2018        August        15  Wednesday     Wednesday
2 2018-10-23       2018       October        23    Tuesday       Tuesday
3 2019-08-17       2019        August        17   Saturday      Saturday
4 2019-01-06       2019       January         6     Sunday        Sunday

In [21]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,10,Tuesday,Tuesday,0
1,2018-08-15,2018,August,15,Wednesday,Wednesday,0
2,2018-10-23,2018,October,23,Tuesday,Tuesday,0
3,2019-08-17,2019,August,17,Saturday,Saturday,1
4,2019-01-06,2019,January,6,Sunday,Sunday,1