<a href="https://colab.research.google.com/github/Ravravan/ML/blob/main/Handling_date_time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [8]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [9]:
#Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

#1.EXTRACT DATE

In [11]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
664 2018-11-05        6543        9       1       2018
97  2018-09-27        4690       23       1       2018
30  2019-07-24        2820       16       4       2019
75  2019-10-12         289       24       1       2019
895 2018-10-31        2714       28       8       2018

#2.EXTRACT MONTH

In [12]:
date['date_month_no'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
982 2019-06-22         354       13       2       2019              6
440 2018-10-31        4382       23       5       2018             10
501 2019-01-24        1881       14      14       2019              1
369 2019-01-02        2357       14      60       2019              1
754 2019-05-03        2323       25     122       2019              5

In [13]:
date['date_month_no'] = date['date'].dt.month_name()
date.sample(5)

          date  product_id  city_id  orders  date_year date_month_no
410 2019-05-17        6309       29       2       2019           May
533 2019-01-22        6291       27       1       2019       January
510 2019-04-04        5953       13      34       2019         April
776 2019-08-18         704       13      10       2019        August
893 2018-08-02        1943       13       1       2018        August

#3. EXTRACT DAYS

In [14]:
date['date_day'] = date['date'].dt.day
date.sample(5)

          date  product_id  city_id  orders  date_year date_month_no  date_day
486 2019-05-20        5822       13       3       2019           May        20
532 2019-10-17        3250       27       3       2019       October        17
154 2018-10-10         803       23       2       2018       October        10
608 2019-04-10        5301       13       1       2019         April        10
53  2019-12-04        5193       16       2       2019      December         4

In [15]:
#day of week
date['date_dow'] = date['date'].dt.dayofweek
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
266,2019-12-11,972,13,1,2019,December,11,2
767,2019-11-30,5117,27,2,2019,November,30,5
633,2018-12-26,4601,26,2,2018,December,26,2
228,2019-05-15,6683,13,8,2019,May,15,2
403,2018-12-03,639,27,1,2018,December,3,0

In [16]:
#day of week - name
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id', 'city_id', 'orders']).head()

        date  date_year date_month_no  date_day  date_dow date_dow_name
0 2019-12-10       2019      December        10         1       Tuesday
1 2018-08-15       2018        August        15         2     Wednesday
2 2018-10-23       2018       October        23         1       Tuesday
3 2019-08-17       2019        August        17         5      Saturday
4 2019-01-06       2019       January         6         6        Sunday

In [17]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,10,1,Tuesday,0
1,2018-08-15,2018,August,15,2,Wednesday,0
2,2018-10-23,2018,October,23,1,Tuesday,0
3,2019-08-17,2019,August,17,5,Saturday,1
4,2019-01-06,2019,January,6,6,Sunday,1

#EXTRACT WEEK OF THE YEAR

In [19]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,December,10,1,Tuesday,0,50
1,2018-08-15,2018,August,15,2,Wednesday,0,33
2,2018-10-23,2018,October,23,1,Tuesday,0,43
3,2019-08-17,2019,August,17,5,Saturday,1,33
4,2019-01-06,2019,January,6,6,Sunday,1,1

#EXTRACT TIME ELAPSED BETWEEN DATES

In [21]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 4, 11, 19, 28, 56, 322554)

In [22]:
today -date['date']

0     2314 days 19:28:56.322554
1     2796 days 19:28:56.322554
2     2727 days 19:28:56.322554
3     2429 days 19:28:56.322554
4     2652 days 19:28:56.322554
                 ...
995   2742 days 19:28:56.322554
996   2683 days 19:28:56.322554
997   2531 days 19:28:56.322554
998   2596 days 19:28:56.322554
999   2370 days 19:28:56.322554
Name: date, Length: 1000, dtype: timedelta64[ns]

In [26]:
(today -date['date']).dt.days

0      2314
1      2796
2      2727
3      2429
4      2652
       ...
995    2742
996    2683
997    2531
998    2596
999    2370
Name: date, Length: 1000, dtype: int64

In [27]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [28]:
#converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [29]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [30]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [32]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [33]:
today - time['date']

0     4500 days 18:38:56.322554
1     4364 days 19:48:56.322554
2     4850 days 19:07:56.322554
3     4152 days 18:57:56.322554
4     4549 days 20:17:56.322554
                 ...
995   5139 days 18:38:56.322554
996   4460 days 20:14:56.322554
997   4925 days 19:51:56.322554
998   5041 days 19:54:56.322554
999   4313 days 20:03:56.322554
Name: date, Length: 1000, dtype: timedelta64[ns]