<a href="https://colab.research.google.com/github/Ravravan/ML/blob/main/softmax_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
encoder = LabelEncoder()
df['species']= encoder.fit_transform(df['species'])

In [8]:
df.sample(20)

     sepal_length  sepal_width  petal_length  petal_width  species
146           6.3          2.5           5.0          1.9        2
54            6.5          2.8           4.6          1.5        1
17            5.1          3.5           1.4          0.3        0
31            5.4          3.4           1.5          0.4        0
63            6.1          2.9           4.7          1.4        1
28            5.2          3.4           1.4          0.2        0
51            6.4          3.2           4.5          1.5        1
29            4.7          3.2           1.6          0.2        0
139           6.9          3.1           5.4          2.1        2
33            5.5          4.2           1.4          0.2        0
19            5.1          3.8           1.5          0.3        0
62            6.0          2.2           4.0          1.0        1
123           6.3          2.7           4.9          1.8        2
55            5.7          2.8           4.5          1.3        1
77            6.7          3.0           5.0          1.7        1
13            4.3          3.0           1.1          0.1        0
53            5.5          2.3           4.0          1.3        1
5             5.4          3.9           1.7          0.4        0
135           7.7          3.0           6.1          2.3        2
27            5.2          3.5           1.5          0.2        0